# run conftest unit tests against terraform code

name: terraform_validator

on:
  pull_request:
    paths:
      - '**.rego'
      - '**.tf'
      - '**.tfvars'

jobs:
  Unit-test-via-Conftest-v0.24.0:
    runs-on: ubuntu-latest
    container:
      image: openpolicyagent/conftest@sha256:8f6fa14accab2f1facef561149894a87edb409d9c4300f800b538eda34fae0c4

    steps:
    - uses: actions/checkout@v2

    - name: Unit test Terraform
      run: |
        conftest test -p ./tests/unit.rego ./roots
